language: generic 
sudo: required
services:
  - docker

before_install:
  - docker build -t bhuwanbhasker/docker-react -f Dockerfile.dev . 

script:
  - docker run -e CI=true bhuwanbhasker/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  edge: true
  region: "us-east-2"
  app: "docker-react-aws"
  env: "DockerReactAws-env"
  bucket_name: "elasticbeanstalk-us-east-2-551180489795"
  bucket_path: "docker-react-aws"
  on:
    branch: master
access_key_id: "AKIAYAVHK2RB5ZXHVCUP"
secret_access_key: "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"